#!/bin/python
'''
filesync
'''
import sys
import json
import click

from utils import logs
from utils import utils
from classes.filesyncconfigs import FilesyncConfigs
from classes.filesyncconnectorlocal import FilesyncConnectorLocal
from classes.filesyncconnectorftp import FilesyncConnectorFtp



@click.command()
@click.option('-i', '--init', 'is_init', type=bool, default=False, show_default=True, is_flag=True, help='Create the base configuration file.')
@click.option('-n', '--new', 'is_new', type=bool, default=False, show_default=True, is_flag=True, help='Create a new configuration with the selected key.')
@click.option('-m', '--modify', 'is_modify', type=bool, default=False, show_default=True, is_flag=True, help='Modify the selected configuration.')
@click.option('-d', '--delete', 'is_delete', type=bool, default=False, show_default=True, is_flag=True, help='Delete the selected configuration.')
@click.option('-a', '--all', 'is_all_key', type=bool, default=False, show_default=True, is_flag=True, help='Execute all the configurations.')
@click.option('-c', '--configs-key', 'configs_key', type=str, default='default', show_default=True, help='Select a configuration key.')
@click.option('-ftph', '--ftp-host', 'ftp_host', type=str, default=None, show_default=True, help='Ftp server for configs.')
@click.option('-ftpp', '--ftp-port', 'ftp_port', type=int, default=21, show_default=True, help='Ftp server port for configs.')
@click.option('-ftpu', '--ftp-user', 'ftp_user', type=str, default=None, show_default=True, help='Ftp user for configs.')
@click.option('-ftppw', '--ftp-password', 'ftp_password', type=str, default=None, show_default=True, help='Ftp password for configs.')
@click.argument('folder-path', type=str, default='.')
def _main(is_init, is_new, is_modify, is_delete, is_all_key, configs_key, ftp_host, ftp_port, ftp_user, ftp_password, folder_path):
    '''
    Sync folders using che filesync-configs.json file inside the FOLDER_PATH folder.
    You must initialize and configure the filesync-configs.json.
    '''
    logs.debug('(filesync._main)', {
        'is_init': is_init,
        'is_new': is_new,
        'is_modify': is_modify,
        'is_delete': is_delete,
        'is_all_key': is_all_key,
        'configs_key': configs_key,
        'ftp_host': ftp_host,
        'ftp_port': ftp_port,
        'ftp_user': ftp_user,
        'ftp_password': ftp_password,
        'folder_path': folder_path
    })
    is_ftp = bool(ftp_host)

    if is_ftp:
        configs_filesync_connector = FilesyncConnectorFtp(folder_path, ftp_host, ftp_port, ftp_user, ftp_password)
    else:
        configs_filesync_connector = FilesyncConnectorLocal(folder_path)

    configs_path = configs_filesync_connector.resolve_path('filesync-configs.json')
    print(f"`configs_path` is `{configs_path}`")

    if is_init:
        configs_filesync_connector.write_file(json.dumps({
            'default': FilesyncConfigs.prompt_create().to_dict()
        }, indent=2).encode(), configs_path)
        sys.exit(0)

    if not configs_filesync_connector.is_entry(configs_path):
        logs.print_red(f"`{configs_path}` not found")
        sys.exit(1)
    if configs_filesync_connector.is_folder(configs_path):
        logs.print_red(f"`{configs_path}` is not a file")
        sys.exit(1)
    filesync_configs_dict_dict = json.loads(configs_filesync_connector.read_file(configs_path))

    if is_new:
        if configs_key == 'default':
            logs.print_red(f"Can't create `{configs_key}` configuration")
            sys.exit(1)
        filesync_configs_dict_dict[configs_key] = FilesyncConfigs.prompt_create().to_dict()
        configs_filesync_connector.write_file(json.dumps(filesync_configs_dict_dict, indent=2).encode(), configs_path)
        sys.exit(0)

    if configs_key not in filesync_configs_dict_dict:
        logs.print_red(f"`{configs_key}` configuration not found")
        sys.exit(1)
    filesync_configs = FilesyncConfigs.from_dict(filesync_configs_dict_dict[configs_key])

    if is_modify:
        filesync_configs_dict_dict[configs_key] = FilesyncConfigs(click.prompt('is_source_ftp', type=bool, default=filesync_configs.is_source_ftp, show_default=True), click.prompt('source_path', type=str, default=filesync_configs.source_path, show_default=True), click.prompt('is_destination_ftp', type=bool, default=filesync_configs.is_destination_ftp, show_default=True), click.prompt('destination_path', type=str, default=filesync_configs.destination_path, show_default=True), click.prompt('is_delete', type=bool, default=filesync_configs.is_delete, show_default=True), click.prompt('is_dual', type=bool, default=filesync_configs.is_dual, show_default=True), click.prompt('ignore_regex_list', type=list, default=[
            *filesync_configs.folder_ignore_regex_list,
            *filesync_configs.file_ignore_regex_list
        ], show_default=True), click.prompt('rename_dict', type=dict, default={
            **filesync_configs.folder_rename_dict,
            **filesync_configs.file_rename_dict
        }, show_default=True)).to_dict()
        configs_filesync_connector.write_file(json.dumps(filesync_configs_dict_dict, indent=2).encode(), configs_path)
        sys.exit(0)

    if is_delete:
        if configs_key == 'default':
            logs.print_red(f"Can't delete `{configs_key}` configuration")
            sys.exit(1)
        del filesync_configs_dict_dict[configs_key]
        configs_filesync_connector.write_file(json.dumps(filesync_configs_dict_dict, indent=2).encode(), configs_path)
        sys.exit(0)

    filesync_configs_list = None
    if is_all_key:
        filesync_configs_list = [FilesyncConfigs.from_dict(filesync_configs_dict) for filesync_configs_dict in filesync_configs_dict_dict.values()]
    else:
        filesync_configs_list = [filesync_configs]

    for filesync_configs in filesync_configs_list:

        source_filesync_connector = None
        if filesync_configs.is_source_ftp:
            source_filesync_connector = FilesyncConnectorFtp(filesync_configs.source_path, click.prompt('source_ftp_host', type=str, default='', show_default=True), click.prompt('source_ftp_port', type=int, default=21, show_default=True), click.prompt('source_ftp_user', type=str, default='', show_default=True), click.prompt('source_ftp_password', type=str, default='', show_default=True, hide_input=True))
        else:
            source_filesync_connector = FilesyncConnectorLocal(filesync_configs.source_path)
        source_path = source_filesync_connector.root_path
        if not source_filesync_connector.is_entry(source_path):
            logs.print_red(f"`{source_path}` not found")
            continue
        if not source_filesync_connector.is_folder(source_path):
            logs.print_red(f"`{source_path}` is not a folder")
            continue
        print(f"`source_path` is `{source_path}`")

        destination_filesync_connector = None
        if filesync_configs.is_source_ftp:
            source_filesync_connector = FilesyncConnectorFtp(filesync_configs.destination_path, click.prompt('destination_ftp_host', type=str, default='', show_default=True), click.prompt('destination_ftp_port', type=int, default=21, show_default=True), click.prompt('destination_ftp_user', type=str, default='', show_default=True), click.prompt('destination_ftp_password', type=str, default='', show_default=True, hide_input=True))
        else:
            destination_filesync_connector = FilesyncConnectorLocal(filesync_configs.destination_path)
        destination_path = destination_filesync_connector.root_path
        if not destination_filesync_connector.is_entry(destination_path):
            logs.print_red(f"`{destination_path}` not found")
            continue
        if not destination_filesync_connector.is_folder(destination_path):
            logs.print_red(f"`{destination_path}` is not a folder")
            continue
        print(f"`destination_path` is `{destination_path}`")

        filesync_configs.folder_rename_dict = {source_filesync_connector.resolve_path(key): destination_filesync_connector.resolve_path(value) for key, value in filesync_configs.folder_rename_dict.items()}
        filesync_configs.file_rename_dict = {source_filesync_connector.resolve_path(key): destination_filesync_connector.resolve_path(value) for key, value in filesync_configs.file_rename_dict.items()}

        if source_path != destination_path:
            utils.sync(source_filesync_connector, source_path, destination_filesync_connector, destination_path, filesync_configs)

        for key, value in filesync_configs.folder_rename_dict.items():
            logs.print_purple(f" || {key} -> {value}")
            if not source_filesync_connector.is_entry(key):
                logs.print_red(f"`{key}` not found")
                continue
            if not source_filesync_connector.is_folder(key):
                logs.print_red(f"`{key}` is not a folder")
                continue
            if not destination_filesync_connector.is_entry(value):
                destination_filesync_connector.make_folder(value)
            elif not destination_filesync_connector.is_folder(value):
                logs.print_red(f"`{value}` is not a folder")
                continue
            logs.print_purple(f" ?? {value}")
            utils.sync(source_filesync_connector, key, destination_filesync_connector, value, filesync_configs)

        for key, value in filesync_configs.file_rename_dict.items():
            logs.print_purple(f" || {key} -> {value}")
            if destination_filesync_connector.is_entry(value):
                if destination_filesync_connector.is_folder(value):
                    logs.print_red(f"`{value}` is not a file")
                    continue
                folder_path = destination_filesync_connector.folder_path(value)
                if not destination_filesync_connector.is_entry(folder_path):
                    destination_filesync_connector.make_folder(folder_path)
                elif not destination_filesync_connector.is_folder(folder_path):
                    logs.print_red(f"`{folder_path}` is not a folder")
                    continue
                if destination_filesync_connector.m_time(key) > destination_filesync_connector.m_time(value):
                    logs.print_green(f" -> {value}")
                    destination_filesync_connector.write_file(destination_filesync_connector.read_file(key), value)
                elif filesync_configs.is_dual and destination_filesync_connector.m_time(value) > destination_filesync_connector.m_time(key):
                    logs.print_blue(f" <- {value}")
                    destination_filesync_connector.write_file(destination_filesync_connector.read_file(value), key)
            else:
                logs.print_green(f" ++ {value}")
                destination_filesync_connector.write_file(source_filesync_connector.read_file(key), value)

        source_filesync_connector.quit()
        source_filesync_connector.quit()



if __name__ == '__main__':
    _main()
